In [5]:
!pip3 install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in /Users/madhvimishra/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.4 in /Users/madhvimishra/Library/Python/3.9/lib/python/site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/madhvimishra/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/madhvimishra/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/madhvimishra/Library/Python/3.9/lib/python/site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)

In [99]:
import pandas as pd     # to work with any of the functions below, we need to exectute thin Blockn again to get the right answer

df= pd.DataFrame({
    "ID": range(1, 21),
    "Name": ["Aarav","Vivaan","Aditya","Vihaan","Arjun","Reyansh","Shaurya","Krishna","Ishaan","Kabir",
             "Rohan","Kunal","Samar","Yash","Dev","Ayaan","Rudra","Om","Aryan","Parth"],
    "Age": [19,20,21,22,20,23,21,22,19,20,21,22,23,20,19,21,22,20,21,23],
    "City": ["Lucknow","Delhi","Mumbai","Pune","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai",
             "Pune","Lucknow","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai","Pune","Lucknow"],
    "Marks": [85,90,78,88,92,76,81,95,89,84,73,77,80,91,87,79,83,86,90,88],
    "Department": ["CS","IT","CS","IT","EC","CS","IT","EC","CS","IT",
                   "EC","CS","IT","EC","CS","IT","EC","CS","IT","EC"],
    "Salary": [30000,32000,28000,35000,40000,27000,33000,42000,31000,34000,
               29000,30000,36000,41000,30500,32500,38000,31500,34500,39500]
})

print(df)
df.to_csv("students_data.csv", index=False) # if you don't write anything in index, it will save the index as well. So, to avoid that, we write index=False
print("Successfully saved the DataFrame to 'students_data.csv'.")

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
1    2   Vivaan   20    Delhi     90         IT   32000
2    3   Aditya   21   Mumbai     78         CS   28000
3    4   Vihaan   22     Pune     88         IT   35000
4    5    Arjun   20   Kanpur     92         EC   40000
5    6  Reyansh   23    Noida     76         CS   27000
6    7  Shaurya   21     Agra     81         IT   33000
7    8  Krishna   22   Jaipur     95         EC   42000
8    9   Ishaan   19    Delhi     89         CS   31000
9   10    Kabir   20   Mumbai     84         IT   34000
10  11    Rohan   21     Pune     73         EC   29000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
13  14     Yash   20    Noida     91         EC   41000
14  15      Dev   19     Agra     87         CS   30500
15  16    Ayaan   21   Jaipur     79         IT   32500
16  17    Rudra   22    Delhi     83         EC   38000
17  18       Om   20   Mumbai     86         CS   31500
18  19    Aryan   21     Pune     90         IT   34500
19  20    Parth   23  Lucknow     88         EC   39500
Successfully saved the DataFrame to 'students_data.csv'.

In [13]:
df.sample(n=5)  # Display a random sample of 5 rows from the DataFrame

    ID     Name  Age    City  Marks Department  Salary
15  16    Ayaan   21  Jaipur     79         IT   32500
16  17    Rudra   22   Delhi     83         EC   38000
6    7  Shaurya   21    Agra     81         IT   33000
9   10    Kabir   20  Mumbai     84         IT   34000
7    8  Krishna   22  Jaipur     95         EC   42000

In [14]:
df.shape    # Display the shape of the DataFrame (number of rows and columns)

(20, 7)

In [15]:
df.head(10)  # Display the first 10 rows of the DataFrame

   ID     Name  Age     City  Marks Department  Salary
0   1    Aarav   19  Lucknow     85         CS   30000
1   2   Vivaan   20    Delhi     90         IT   32000
2   3   Aditya   21   Mumbai     78         CS   28000
3   4   Vihaan   22     Pune     88         IT   35000
4   5    Arjun   20   Kanpur     92         EC   40000
5   6  Reyansh   23    Noida     76         CS   27000
6   7  Shaurya   21     Agra     81         IT   33000
7   8  Krishna   22   Jaipur     95         EC   42000
8   9   Ishaan   19    Delhi     89         CS   31000
9  10    Kabir   20   Mumbai     84         IT   34000

In [16]:
df.tail(10)  # Display the last 10 rows of the DataFrame

    ID   Name  Age     City  Marks Department  Salary
10  11  Rohan   21     Pune     73         EC   29000
11  12  Kunal   22  Lucknow     77         CS   30000
12  13  Samar   23   Kanpur     80         IT   36000
13  14   Yash   20    Noida     91         EC   41000
14  15    Dev   19     Agra     87         CS   30500
15  16  Ayaan   21   Jaipur     79         IT   32500
16  17  Rudra   22    Delhi     83         EC   38000
17  18     Om   20   Mumbai     86         CS   31500
18  19  Aryan   21     Pune     90         IT   34500
19  20  Parth   23  Lucknow     88         EC   39500

In [17]:
df.columns  # Display the column names of the DataFrame

Index(['ID', 'Name', 'Age', 'City', 'Marks', 'Department', 'Salary'], dtype='object')

In [18]:
df.index  # Display the index of the DataFrame

RangeIndex(start=0, stop=20, step=1)

In [19]:
df.dtypes  # Display the data types of each column in the DataFrame

ID             int64
Name          object
Age            int64
City          object
Marks          int64
Department    object
Salary         int64
dtype: object

In [26]:
df.info()  # Display information about the DataFrame, including data types and non-null counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          20 non-null     int64
 1   Name        20 non-null     object
 2   Age         20 non-null     int64
 3   City        20 non-null     object
 4   Marks       20 non-null     int64
 5   Department  20 non-null     object
 6   Salary      20 non-null     int64
dtypes: int64(4), object(3)
memory usage: 1.2+ KB

In [27]:
df.describe()  # Display summary statistics for numerical columns in the DataFrame

             ID        Age      Marks       Salary
count  20.00000  20.000000  20.000000     20.00000
mean   10.50000  20.950000  84.600000  33725.00000
std     5.91608   1.316894   6.029751   4446.98301
min     1.00000  19.000000  73.000000  27000.00000
25%     5.75000  20.000000  79.750000  30375.00000
50%    10.50000  21.000000  85.500000  32750.00000
75%    15.25000  22.000000  89.250000  36500.00000
max    20.00000  23.000000  95.000000  42000.00000

In [28]:
print(df.loc[0])  # Display the first row of the DataFrame using .loc

ID                  1
Name            Aarav
Age                19
City          Lucknow
Marks              85
Department         CS
Salary          30000
Name: 0, dtype: object

In [29]:
print(df.iloc[0])  # Display the first row of the DataFrame using .iloc

ID                  1
Name            Aarav
Age                19
City          Lucknow
Marks              85
Department         CS
Salary          30000
Name: 0, dtype: object

In [34]:
print(df.loc[1:5])  # Display rows from index 1 to 5 using .loc

   ID     Name  Age    City  Marks Department  Salary
1   2   Vivaan   20   Delhi     90         IT   32000
2   3   Aditya   21  Mumbai     78         CS   28000
3   4   Vihaan   22    Pune     88         IT   35000
4   5    Arjun   20  Kanpur     92         EC   40000
5   6  Reyansh   23   Noida     76         CS   27000

In [35]:
bool_idx=df['Age'] > 21  # Create a boolean index for rows where Age is greater than 21
df[bool_idx]  # Use the boolean index to filter the DataFrame

    ID     Name  Age     City  Marks Department  Salary
3    4   Vihaan   22     Pune     88         IT   35000
5    6  Reyansh   23    Noida     76         CS   27000
7    8  Krishna   22   Jaipur     95         EC   42000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
16  17    Rudra   22    Delhi     83         EC   38000
19  20    Parth   23  Lucknow     88         EC   39500

In [36]:
df.sort_values(by='Marks', ascending=False)  # Sort the DataFrame by the 'Marks' column in descending order

    ID     Name  Age     City  Marks Department  Salary
7    8  Krishna   22   Jaipur     95         EC   42000
4    5    Arjun   20   Kanpur     92         EC   40000
13  14     Yash   20    Noida     91         EC   41000
1    2   Vivaan   20    Delhi     90         IT   32000
18  19    Aryan   21     Pune     90         IT   34500
8    9   Ishaan   19    Delhi     89         CS   31000
19  20    Parth   23  Lucknow     88         EC   39500
3    4   Vihaan   22     Pune     88         IT   35000
14  15      Dev   19     Agra     87         CS   30500
17  18       Om   20   Mumbai     86         CS   31500
0    1    Aarav   19  Lucknow     85         CS   30000
9   10    Kabir   20   Mumbai     84         IT   34000
16  17    Rudra   22    Delhi     83         EC   38000
6    7  Shaurya   21     Agra     81         IT   33000
12  13    Samar   23   Kanpur     80         IT   36000
15  16    Ayaan   21   Jaipur     79         IT   32500
2    3   Aditya   21   Mumbai     78         CS   28000
11  12    Kunal   22  Lucknow     77         CS   30000
5    6  Reyansh   23    Noida     76         CS   27000
10  11    Rohan   21     Pune     73         EC   29000

In [38]:
df.sort_index(ascending=False)  # Sort the DataFrame by its index in descending order

    ID     Name  Age     City  Marks Department  Salary
19  20    Parth   23  Lucknow     88         EC   39500
18  19    Aryan   21     Pune     90         IT   34500
17  18       Om   20   Mumbai     86         CS   31500
16  17    Rudra   22    Delhi     83         EC   38000
15  16    Ayaan   21   Jaipur     79         IT   32500
14  15      Dev   19     Agra     87         CS   30500
13  14     Yash   20    Noida     91         EC   41000
12  13    Samar   23   Kanpur     80         IT   36000
11  12    Kunal   22  Lucknow     77         CS   30000
10  11    Rohan   21     Pune     73         EC   29000
9   10    Kabir   20   Mumbai     84         IT   34000
8    9   Ishaan   19    Delhi     89         CS   31000
7    8  Krishna   22   Jaipur     95         EC   42000
6    7  Shaurya   21     Agra     81         IT   33000
5    6  Reyansh   23    Noida     76         CS   27000
4    5    Arjun   20   Kanpur     92         EC   40000
3    4   Vihaan   22     Pune     88         IT   35000
2    3   Aditya   21   Mumbai     78         CS   28000
1    2   Vivaan   20    Delhi     90         IT   32000
0    1    Aarav   19  Lucknow     85         CS   30000

In [94]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,116,117,118,119,120],

    "Name": ["Aman","Riya",None,"Karan","Priya","Rahul","Neha",None,
             "Vikas","Pooja","Ankit","Simran","Rohit",None,"Kajal",
             "Deepak","Meena","Arjun","Nisha",None],

    "Age": [20,21,np.nan,22,19,23,21,20,np.nan,22,
            24,23,21,20,22,np.nan,19,21,23,20],

    "City": ["Delhi","Mumbai","Pune",None,"Jaipur","Delhi","Mumbai",
             "Pune","Delhi",None,"Jaipur","Mumbai","Delhi","Pune",
             None,"Delhi","Mumbai","Jaipur","Pune","Delhi"],

    "Marks": [85,90,78,np.nan,88,76,91,82,95,np.nan,
              80,84,79,92,87,75,np.nan,89,81,93]
})

print(df)

    Student_ID    Name   Age    City  Marks
0          101    Aman  20.0   Delhi   85.0
1          102    Riya  21.0  Mumbai   90.0
2          103    None   NaN    Pune   78.0
3          104   Karan  22.0    None    NaN
4          105   Priya  19.0  Jaipur   88.0
5          106   Rahul  23.0   Delhi   76.0
6          107    Neha  21.0  Mumbai   91.0
7          108    None  20.0    Pune   82.0
8          109   Vikas   NaN   Delhi   95.0
9          110   Pooja  22.0    None    NaN
10         111   Ankit  24.0  Jaipur   80.0
11         112  Simran  23.0  Mumbai   84.0
12         113   Rohit  21.0   Delhi   79.0
13         114    None  20.0    Pune   92.0
14         115   Kajal  22.0    None   87.0
15         116  Deepak   NaN   Delhi   75.0
16         117   Meena  19.0  Mumbai    NaN
17         118   Arjun  21.0  Jaipur   89.0
18         119   Nisha  23.0    Pune   81.0
19         120    None  20.0   Delhi   93.0

In [69]:
df.isnull()  # Check for missing values in the DataFrame

    Student_ID   Name    Age   City  Marks
0        False  False  False  False  False
1        False  False  False  False  False
2        False   True   True  False  False
3        False  False  False   True   True
4        False  False  False  False  False
5        False  False  False  False  False
6        False  False  False  False  False
7        False   True  False  False  False
8        False  False   True  False  False
9        False  False  False   True   True
10       False  False  False  False  False
11       False  False  False  False  False
12       False  False  False  False  False
13       False   True  False  False  False
14       False  False  False   True  False
15       False  False   True  False  False
16       False  False  False  False   True
17       False  False  False  False  False
18       False  False  False  False  False
19       False   True  False  False  False

In [74]:
df.dropna()  # Drop rows with any missing values from the DataFrame
print(df)

    Student_ID     Name   Age     City  Marks
0          101     Aman  20.0    Delhi   85.0
1          102     Riya  21.0   Mumbai   90.0
2          103  Unknown   0.0     Pune   78.0
3          104    Karan  22.0  Unknown    0.0
4          105    Priya  19.0   Jaipur   88.0
5          106    Rahul  23.0    Delhi   76.0
6          107     Neha  21.0   Mumbai   91.0
7          108  Unknown  20.0     Pune   82.0
8          109    Vikas   0.0    Delhi   95.0
9          110    Pooja  22.0  Unknown    0.0
10         111    Ankit  24.0   Jaipur   80.0
11         112   Simran  23.0   Mumbai   84.0
12         113    Rohit  21.0    Delhi   79.0
13         114  Unknown  20.0     Pune   92.0
14         115    Kajal  22.0  Unknown   87.0
15         116   Deepak   0.0    Delhi   75.0
16         117    Meena  19.0   Mumbai    0.0
17         118    Arjun  21.0   Jaipur   89.0
18         119    Nisha  23.0     Pune   81.0
19         120  Unknown  20.0    Delhi   93.0

In [71]:
df.fillna(0)  # Fill missing values with 0
print(df)

    Student_ID     Name   Age     City  Marks
0          101     Aman  20.0    Delhi   85.0
1          102     Riya  21.0   Mumbai   90.0
2          103  Unknown   0.0     Pune   78.0
3          104    Karan  22.0  Unknown    0.0
4          105    Priya  19.0   Jaipur   88.0
5          106    Rahul  23.0    Delhi   76.0
6          107     Neha  21.0   Mumbai   91.0
7          108  Unknown  20.0     Pune   82.0
8          109    Vikas   0.0    Delhi   95.0
9          110    Pooja  22.0  Unknown    0.0
10         111    Ankit  24.0   Jaipur   80.0
11         112   Simran  23.0   Mumbai   84.0
12         113    Rohit  21.0    Delhi   79.0
13         114  Unknown  20.0     Pune   92.0
14         115    Kajal  22.0  Unknown   87.0
15         116   Deepak   0.0    Delhi   75.0
16         117    Meena  19.0   Mumbai    0.0
17         118    Arjun  21.0   Jaipur   89.0
18         119    Nisha  23.0     Pune   81.0
19         120  Unknown  20.0    Delhi   93.0

In [ ]:
df.fillna(value={'Name': 'Unknown', 'City': 'Unknown', 'Age': 0, 'Marks': 0}, inplace=True)  # Fill missing values with specified values in place
print(df)

    Student_ID     Name   Age     City  Marks
0          101     Aman  20.0    Delhi   85.0
1          102     Riya  21.0   Mumbai   90.0
2          103  Unknown   0.0     Pune   78.0
3          104    Karan  22.0  Unknown    0.0
4          105    Priya  19.0   Jaipur   88.0
5          106    Rahul  23.0    Delhi   76.0
6          107     Neha  21.0   Mumbai   91.0
7          108  Unknown  20.0     Pune   82.0
8          109    Vikas   0.0    Delhi   95.0
9          110    Pooja  22.0  Unknown    0.0
10         111    Ankit  24.0   Jaipur   80.0
11         112   Simran  23.0   Mumbai   84.0
12         113    Rohit  21.0    Delhi   79.0
13         114  Unknown  20.0     Pune   92.0
14         115    Kajal  22.0  Unknown   87.0
15         116   Deepak   0.0    Delhi   75.0
16         117    Meena  19.0   Mumbai    0.0
17         118    Arjun  21.0   Jaipur   89.0
18         119    Nisha  23.0     Pune   81.0
19         120  Unknown  20.0    Delhi   93.0

In [80]:
mean_marks = df['Marks'].mean()  # Calculate the mean of the 'Marks' column
print(mean_marks)

85.0

In [93]:
df.fillna(value = {'Name': 'Unknown', 'City': 'Unknown', 'Age': 0, 'Marks': mean_marks}, inplace=True)  # Fill missing values with specified values in place
df['Marks'].replace(to_replace=np.nan, value=mean_marks, inplace=True)  # Replace missing values in 'Marks' with the mean
print(df)

    Student_ID     Name   Age     City  Marks
0          101     Aman  20.0    Delhi   85.0
1          102     Riya  21.0   Mumbai   90.0
2          103  Unknown   0.0     Pune   78.0
3          104    Karan  22.0  Unknown   85.0
4          105    Priya  19.0   Jaipur   88.0
5          106    Rahul  23.0    Delhi   76.0
6          107     Neha  21.0   Mumbai   91.0
7          108  Unknown  20.0     Pune   82.0
8          109    Vikas   0.0    Delhi   95.0
9          110    Pooja  22.0  Unknown   85.0
10         111    Ankit  24.0   Jaipur   80.0
11         112   Simran  23.0   Mumbai   84.0
12         113    Rohit  21.0    Delhi   79.0
13         114  Unknown  20.0     Pune   92.0
14         115    Kajal  22.0  Unknown   87.0
15         116   Deepak   0.0    Delhi   75.0
16         117    Meena  19.0   Mumbai   85.0
17         118    Arjun  21.0   Jaipur   89.0
18         119    Nisha  23.0     Pune   81.0
19         120  Unknown  20.0    Delhi   93.0

/var/folders/gy/xv2qh7cn43n_nc0d_x6gx8zw0000gn/T/ipykernel_87262/4215297419.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Marks'].replace(to_replace=np.nan, value=mean_marks, inplace=True)  # Replace missing values in 'Marks' with the mean


Show all students whose Marks > 85

Show all students whose Age is 20

Show all students who live in Delhi

Show all students who live in Mumbai

Show all students whose Salary > 35000

Show all students whose Marks < 80

Show all students whose Age > 21

Show all students whose Department is CS

Show all students whose Department is IT

Show all students whose City is Lucknow

In [ ]:
import pandas as pd     # to work with any of the functions below, we need to exectute thin Blockn again to get the right answer

df= pd.DataFrame({
    "ID": range(1, 21),
    "Name": ["Aarav","Vivaan","Aditya","Vihaan","Arjun","Reyansh","Shaurya","Krishna","Ishaan","Kabir",
             "Rohan","Kunal","Samar","Yash","Dev","Ayaan","Rudra","Om","Aryan","Parth"],
    "Age": [19,20,21,22,20,23,21,22,19,20,21,22,23,20,19,21,22,20,21,23],
    "City": ["Lucknow","Delhi","Mumbai","Pune","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai",
             "Pune","Lucknow","Kanpur","Noida","Agra","Jaipur","Delhi","Mumbai","Pune","Lucknow"],
    "Marks": [85,90,78,88,92,76,81,95,89,84,73,77,80,91,87,79,83,86,90,88],
    "Department": ["CS","IT","CS","IT","EC","CS","IT","EC","CS","IT",
                   "EC","CS","IT","EC","CS","IT","EC","CS","IT","EC"],
    "Salary": [30000,32000,28000,35000,40000,27000,33000,42000,31000,34000,
               29000,30000,36000,41000,30500,32500,38000,31500,34500,39500]
})

print(df)
df.to_csv("students_data.csv", index=False) # if you don't write anything in index, it will save the index as well. So, to avoid that, we write index=False
print("Successfully saved the DataFrame to 'students_data.csv'.")

In [122]:
bool_idx = df['Marks'] >85
print(df[bool_idx])

    ID     Name  Age     City  Marks Department  Salary
1    2   Vivaan   20    Delhi     90         IT   32000
3    4   Vihaan   22     Pune     88         IT   35000
4    5    Arjun   20   Kanpur     92         EC   40000
7    8  Krishna   22   Jaipur     95         EC   42000
8    9   Ishaan   19    Delhi     89         CS   31000
13  14     Yash   20    Noida     91         EC   41000
14  15      Dev   19     Agra     87         CS   30500
17  18       Om   20   Mumbai     86         CS   31500
18  19    Aryan   21     Pune     90         IT   34500
19  20    Parth   23  Lucknow     88         EC   39500

In [102]:
bool_idx = df['Age'] == 20
print(df[bool_idx])

    ID    Name  Age    City  Marks Department  Salary
1    2  Vivaan   20   Delhi     90         IT   32000
4    5   Arjun   20  Kanpur     92         EC   40000
9   10   Kabir   20  Mumbai     84         IT   34000
13  14    Yash   20   Noida     91         EC   41000
17  18      Om   20  Mumbai     86         CS   31500

In [101]:
bool_idx = df['City'] == 'Delhi'
print(df[bool_idx])

    ID    Name  Age   City  Marks Department  Salary
1    2  Vivaan   20  Delhi     90         IT   32000
8    9  Ishaan   19  Delhi     89         CS   31000
16  17   Rudra   22  Delhi     83         EC   38000

In [100]:
bool_idx = df['City'] == 'Mumbai'
print(df[bool_idx])

    ID    Name  Age    City  Marks Department  Salary
2    3  Aditya   21  Mumbai     78         CS   28000
9   10   Kabir   20  Mumbai     84         IT   34000
17  18      Om   20  Mumbai     86         CS   31500

In [ ]:
bool_idx = df['Salary'] > 35000
print(df[bool_idx])

    ID     Name  Age     City  Marks Department  Salary
4    5    Arjun   20   Kanpur     92         EC   40000
7    8  Krishna   22   Jaipur     95         EC   42000
12  13    Samar   23   Kanpur     80         IT   36000
13  14     Yash   20    Noida     91         EC   41000
16  17    Rudra   22    Delhi     83         EC   38000
19  20    Parth   23  Lucknow     88         EC   39500

In [105]:
bool_idx = df['Marks'] < 80
print(df[bool_idx])

    ID     Name  Age     City  Marks Department  Salary
2    3   Aditya   21   Mumbai     78         CS   28000
5    6  Reyansh   23    Noida     76         CS   27000
10  11    Rohan   21     Pune     73         EC   29000
11  12    Kunal   22  Lucknow     77         CS   30000
15  16    Ayaan   21   Jaipur     79         IT   32500

In [106]:
bool_idx = df['Age'] > 21
print(df[bool_idx])

    ID     Name  Age     City  Marks Department  Salary
3    4   Vihaan   22     Pune     88         IT   35000
5    6  Reyansh   23    Noida     76         CS   27000
7    8  Krishna   22   Jaipur     95         EC   42000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
16  17    Rudra   22    Delhi     83         EC   38000
19  20    Parth   23  Lucknow     88         EC   39500

In [108]:
bool_idx = (df['Department'] == 'CS') | (df['Department'] == 'IT')
print(df[bool_idx])

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
1    2   Vivaan   20    Delhi     90         IT   32000
2    3   Aditya   21   Mumbai     78         CS   28000
3    4   Vihaan   22     Pune     88         IT   35000
5    6  Reyansh   23    Noida     76         CS   27000
6    7  Shaurya   21     Agra     81         IT   33000
8    9   Ishaan   19    Delhi     89         CS   31000
9   10    Kabir   20   Mumbai     84         IT   34000
11  12    Kunal   22  Lucknow     77         CS   30000
12  13    Samar   23   Kanpur     80         IT   36000
14  15      Dev   19     Agra     87         CS   30500
15  16    Ayaan   21   Jaipur     79         IT   32500
17  18       Om   20   Mumbai     86         CS   31500
18  19    Aryan   21     Pune     90         IT   34500

In [109]:
bool_idx = df['City'] == 'Lucknow'
print(df[bool_idx])

    ID   Name  Age     City  Marks Department  Salary
0    1  Aarav   19  Lucknow     85         CS   30000
11  12  Kunal   22  Lucknow     77         CS   30000
19  20  Parth   23  Lucknow     88         EC   39500


Show students whose Marks > 80 AND Age < 21

Show students from Delhi AND Marks > 85

Show students from Mumbai OR Pune

Show students NOT from Lucknow

Show students whose Marks between 80 and 90

Show students whose Department is CS OR EC

Show students whose Salary > 32000 AND Department is IT

Show students whose Age is 21 OR Marks > 90

Show students whose City is Delhi, Mumbai, or Lucknow

Show students whose Marks > 85 AND Age >= 20

In [110]:
bool_idx = (df['Age'] < 21) & (df['Marks'] > 80)
print(df[bool_idx])

    ID    Name  Age     City  Marks Department  Salary
0    1   Aarav   19  Lucknow     85         CS   30000
1    2  Vivaan   20    Delhi     90         IT   32000
4    5   Arjun   20   Kanpur     92         EC   40000
8    9  Ishaan   19    Delhi     89         CS   31000
9   10   Kabir   20   Mumbai     84         IT   34000
13  14    Yash   20    Noida     91         EC   41000
14  15     Dev   19     Agra     87         CS   30500
17  18      Om   20   Mumbai     86         CS   31500

In [111]:
bool_idx = (df['City'] == 'Delhi') & (df['Marks'] > 85)
print(df[bool_idx])

   ID    Name  Age   City  Marks Department  Salary
1   2  Vivaan   20  Delhi     90         IT   32000
8   9  Ishaan   19  Delhi     89         CS   31000

In [112]:
bool_idx = (df['City'] == 'Mumbai') | (df['City'] == 'Pune')
print(df[bool_idx])

    ID    Name  Age    City  Marks Department  Salary
2    3  Aditya   21  Mumbai     78         CS   28000
3    4  Vihaan   22    Pune     88         IT   35000
9   10   Kabir   20  Mumbai     84         IT   34000
10  11   Rohan   21    Pune     73         EC   29000
17  18      Om   20  Mumbai     86         CS   31500
18  19   Aryan   21    Pune     90         IT   34500

In [113]:
bool_idx = df['City'] != 'Lucknow'
print(df[bool_idx])

    ID     Name  Age    City  Marks Department  Salary
1    2   Vivaan   20   Delhi     90         IT   32000
2    3   Aditya   21  Mumbai     78         CS   28000
3    4   Vihaan   22    Pune     88         IT   35000
4    5    Arjun   20  Kanpur     92         EC   40000
5    6  Reyansh   23   Noida     76         CS   27000
6    7  Shaurya   21    Agra     81         IT   33000
7    8  Krishna   22  Jaipur     95         EC   42000
8    9   Ishaan   19   Delhi     89         CS   31000
9   10    Kabir   20  Mumbai     84         IT   34000
10  11    Rohan   21    Pune     73         EC   29000
12  13    Samar   23  Kanpur     80         IT   36000
13  14     Yash   20   Noida     91         EC   41000
14  15      Dev   19    Agra     87         CS   30500
15  16    Ayaan   21  Jaipur     79         IT   32500
16  17    Rudra   22   Delhi     83         EC   38000
17  18       Om   20  Mumbai     86         CS   31500
18  19    Aryan   21    Pune     90         IT   34500

In [115]:
bool_idx = (df['Marks'] > 80) & (df['Marks'] < 90)
print(df[bool_idx])

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
3    4   Vihaan   22     Pune     88         IT   35000
6    7  Shaurya   21     Agra     81         IT   33000
8    9   Ishaan   19    Delhi     89         CS   31000
9   10    Kabir   20   Mumbai     84         IT   34000
14  15      Dev   19     Agra     87         CS   30500
16  17    Rudra   22    Delhi     83         EC   38000
17  18       Om   20   Mumbai     86         CS   31500
19  20    Parth   23  Lucknow     88         EC   39500

In [116]:
bool_idx = (df['Department'] == 'CS') | (df['Department'] == 'EC')
print(df[bool_idx])

    ID     Name  Age     City  Marks Department  Salary
0    1    Aarav   19  Lucknow     85         CS   30000
2    3   Aditya   21   Mumbai     78         CS   28000
4    5    Arjun   20   Kanpur     92         EC   40000
5    6  Reyansh   23    Noida     76         CS   27000
7    8  Krishna   22   Jaipur     95         EC   42000
8    9   Ishaan   19    Delhi     89         CS   31000
10  11    Rohan   21     Pune     73         EC   29000
11  12    Kunal   22  Lucknow     77         CS   30000
13  14     Yash   20    Noida     91         EC   41000
14  15      Dev   19     Agra     87         CS   30500
16  17    Rudra   22    Delhi     83         EC   38000
17  18       Om   20   Mumbai     86         CS   31500
19  20    Parth   23  Lucknow     88         EC   39500

In [117]:
bool_idx = (df['Salary'] > 32000) & (df['Department'] == 'IT')
print(df[bool_idx])

    ID     Name  Age    City  Marks Department  Salary
3    4   Vihaan   22    Pune     88         IT   35000
6    7  Shaurya   21    Agra     81         IT   33000
9   10    Kabir   20  Mumbai     84         IT   34000
12  13    Samar   23  Kanpur     80         IT   36000
15  16    Ayaan   21  Jaipur     79         IT   32500
18  19    Aryan   21    Pune     90         IT   34500

In [119]:
bool_idx = (df['Age'] == 21) & (df['Marks'] >= 90)
print(df[bool_idx])

    ID   Name  Age  City  Marks Department  Salary
18  19  Aryan   21  Pune     90         IT   34500

In [120]:
bool_idx = (df['City'] == 'Lucknow') | (df['City'] == 'Delhi') | (df['City'] == 'Mumbai')
print(df[bool_idx])

    ID    Name  Age     City  Marks Department  Salary
0    1   Aarav   19  Lucknow     85         CS   30000
1    2  Vivaan   20    Delhi     90         IT   32000
2    3  Aditya   21   Mumbai     78         CS   28000
8    9  Ishaan   19    Delhi     89         CS   31000
9   10   Kabir   20   Mumbai     84         IT   34000
11  12   Kunal   22  Lucknow     77         CS   30000
16  17   Rudra   22    Delhi     83         EC   38000
17  18      Om   20   Mumbai     86         CS   31500
19  20   Parth   23  Lucknow     88         EC   39500

In [121]:
bool_idx = (df['Age'] >= 21) & (df['Marks'] > 85)
print(df[bool_idx])

    ID     Name  Age     City  Marks Department  Salary
3    4   Vihaan   22     Pune     88         IT   35000
7    8  Krishna   22   Jaipur     95         EC   42000
18  19    Aryan   21     Pune     90         IT   34500
19  20    Parth   23  Lucknow     88         EC   39500